CC = gcc
CFLAGS := -Wall -Wextra -std=gnu89 -g
SRC := ../../src/
INCLUDES := -I ../../include
NAME := complex_progress_bar_test


run:
	$(CC) $(CFLAGS) $(NAME).c $(SRC)probar.c -o $(NAME) $(INCLUDES)
	./$(NAME)
